language: bash

before_install:
    - sudo apt-get update
    
install:
    - sudo apt-get install build-essential libxerces-c-dev libpq-dev curl libcurl4-gnutls-dev libxml2-dev libexpat1-dev libsqlite3-dev python-gdal
    - sudo bash install-gdal.sh
    
script:
    - python python/ogr-check-version.py
    - python python/ogr-gfs-tester.py data/annex1/ad-address-deegree-demo.gml gfs/annex1/ad-Address.gfs
